version: "1.1"
services:
  setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    volumes:
      - ./.secrets:/credentials:ro
    command: /bin/sh -c './initial_setup && exit 0'
  webserver:
    build:
          context: .
          dockerfile: Dockerfile.main
    volumes:
      - ./.secrets:/credentials:ro
    ports:
      - '8080'
    deploy:
      replicas: 4
    restart: unless-stopped
    depends_on:
      - setup
  loadbalancer:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver